// js/data.js

const initialData = {
    "Rotuladeira": [
        { "id": "Rotuladeira_0", "acao": "Colocar as correntes", "detalhamento": "Colocar as correntes do separador e guiar dos frascos que estão faltando", "levantamento": "Julio", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_1", "acao": "Reaperto e Limpeza do Painel Local", "detalhamento": "Desenergizar, inspecionar bornes, contatores e disjuntores. Realizar reaperto geral com torquímetro e limpeza com limpa-contato.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_2", "acao": "Inspeção de Sensores Fotocélulas", "detalhamento": "Limpar lentes dos sensores de leitura de frasco e rótulo. Verificar alinhamento, fixação e integridade do cabeamento.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_3", "acao": "Verificação de Aterramento e Potência", "detalhamento": "Medir resistência de isolação e continuidade do aterramento do motor principal e painel.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_4", "acao": "Ajuste de guias e roletes", "detalhamento": "Alinhar as guias de entrada dos frascos e substituir roletes com desgaste que causam travamento.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_5", "acao": "Tensionamento das correias", "detalhamento": "Verificar e ajustar o tensionamento das correias de tração para evitar deslizamento do rótulo.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_6", "acao": "Limpeza e lubrificação", "detalhamento": "Realizar Limpeza e lubrificação engrenagens do aplicador.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_7", "acao": "Revisão dos sensores ópticos", "detalhamento": "Limpar as lentes e refazer a calibração do sensor de presença de rótulo.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Rotuladeira_8", "acao": "Reaperto do motoredutor", "detalhamento": "Reapertar os bornes de alimentação do motoredutor principal para prevenir mau contato.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" }
    ],
    "Tampadeira": [
        { "id": "Tampadeira_0", "acao": "Troca dos rolamentos do eixo principal.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_1", "acao": "Troca das buchas e astes dos conjuntos dos pedestais.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_2", "acao": "Troca dos acionadores das castanhas.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_3", "acao": "Troca dos dedos e molas das castanhas.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_4", "acao": "Troca do rotativo de entrada de ar.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_5", "acao": "Troca da valvula reguladora do anti-giro.", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_6", "acao": "Troca dos rolamentos e terminais do conjunto desviador", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_7", "acao": "Troca dos rolamentos do eixo da estrela de saída", "detalhamento": "Retro alimentar os planos de preventiva, sejam eles os periodicos ou as inspeções.", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Tampadeira_8", "acao": "Manutenção do Quadro de Comando", "detalhamento": "Verificar ventilação do painel, trocar filtros de ar se necessário. Reaperto geral nas conexões de potência.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_9", "acao": "Teste de Segurança (NR-12)", "detalhamento": "Acionar todos os botões de emergência, chaves fim de curso e intertravamentos de portas. Validar atuação imediata do relé de segurança.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_10", "acao": "Inspeção do Chicote Elétrico (Móvel)", "detalhamento": "Avaliar estado das esteiras porta-cabos e chicotes flexíveis, buscando por condutores expostos ou ressecados devido à fadiga mecânica.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_11", "acao": "Calibração do torque do mandril", "detalhamento": "Ajustar a mola e a fricção dos mandris de fechamento para garantir o torque especificado.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_12", "acao": "Desobstrução do canal de descida", "detalhamento": "Limpar canaleta de tampas e ajustar o ângulo para evitar o enrosco durante a queda.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_13", "acao": "Lubrificação dos cames", "detalhamento": "Inspecionar e lubrificar a pista do came de elevação dos cabeçotes.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Tampadeira_14", "acao": "Inspeção elétrica do painel", "detalhamento": "Medição de correntes dos motores e reaperto geral dos disjuntores do cabeçote.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" }
    ],
    "Elevador de Tampas": [
        { "id": "Elevador_0", "acao": "Troca da esteira", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_1", "acao": "Troca dos rolamentos dos mancais de tração e esticador", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_2", "acao": "Troca do rolete de tração da esteira", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Elevador_3", "acao": "Revisão do motorredutor de acionamento do elevador", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Elevador_4", "acao": "Troca do fole de saída do elevador", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Elevador_5", "acao": "Refazer rosca de fixação do reservatório de tampas do litro", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_6", "acao": "Revisão do motorredutor do distribuidor de tampas do litro", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Elevador_7", "acao": "Revisão do motorredutor do distribuidor de tampas do 150ml", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_8", "acao": "Refazer rosca de fixação do reservatório de tampas do 150ml", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_9", "acao": "Aferição dos Sensores de Nível", "detalhamento": "Testar atuação dos sensores capacitivos/óticos no reservatório para garantir sinalização correta de 'nivel alto' e 'nivel baixo'.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_10", "acao": "Medição de Corrente dos Motorredutores", "detalhamento": "Com equipamento em carga, medir tensão e corrente dos motores do elevador e distribuidor. Comparar com corrente nominal da placa.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_11", "acao": "Ajuste de tensão da esteira", "detalhamento": "Esticar a lona de transporte para corrigir desalinhamentos laterais.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_12", "acao": "Troca de taliscas avariadas", "detalhamento": "Identificar e substituir as taliscas quebradas da esteira modular.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_13", "acao": "Inspeção de mancais", "detalhamento": "Inspecionar ruido e lubrificar mancais dos eixos superior e inferior.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_14", "acao": "Calibração do sensor da moega", "detalhamento": "Ajustar a sensibilidade do sensor capacitivo de nível para evitar falhas de abastecimento.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Elevador_15", "acao": "Teste do circuito de emergência", "detalhamento": "Acionar botões de emergência e verificar tempo de parada e sinalização no painel.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" }
    ],
    "Enchedora": [
        { "id": "Enchedora_0", "acao": "Troca dos rolamentos dos mancais das roscas posicionadoras", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_1", "acao": "Troca dos 'garfos', eixos e conectores dos cilindros de acionamento dos bicos dosadores", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_2", "acao": "Troca das mangueiras de alimentação e distribuição de ar", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_3", "acao": "Troca das eletroválvulas de acionamento dos bicos dosadores", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_4", "acao": "Troca da borracha de vedação da porta de inspeção", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_5", "acao": "Troca das correias do motor principal", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_6", "acao": "Troca do rotativo de entrada de ar", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_7", "acao": "Revisão do redutor principal", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_8", "acao": "Revisão da valvula de entrada de produto", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_9", "acao": "Troca dos reparos das valvulas do sistema de lavagem", "detalhamento": "-", "levantamento": "Donizete Saravale", "execucao": "Orivaldo Camassuti", "previsao": "A DECIDIR", "status": "Pendente" },
        { "id": "Enchedora_10", "acao": "Termografia e Reaperto no Painel Principal", "detalhamento": "Realizar inspeção termográfica buscando pontos de aquecimento. Executar reaperto geral após esfriamento.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_11", "acao": "Revisão Elétrica das Eletroválvulas", "detalhamento": "Checar fiação e conectores (plugs) das válvulas de envase e lavagem. Garantir vedação contra umidade (grau de proteção IP).", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_12", "acao": "Teste da Malha de Aterramento", "detalhamento": "Crucial pelo contato com líquidos: Medir a continuidade da carcaça metálica com o barramento de terra do painel. Garantir eliminação de fuga de corrente.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_13", "acao": "Substituição de vedações dos bicos", "detalhamento": "Trocar os o-rings das bicos de envase que apresentam gotejamento.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_14", "acao": "Alinhamento das estrelas", "detalhamento": "Ajustar o sincronismo mecânico das estrelas de entrada e saída.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_15", "acao": "Lubrificação de guias lineares", "detalhamento": "Lubrificar as hastes dos pistões de elevação de frascos para movimento suave.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_16", "acao": "Teste das válvulas solenoides", "detalhamento": "Verificar tempo de resposta das válvulas de envase e limpar conectores elétricos.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Enchedora_17", "acao": "Medição da fonte 24VDC", "detalhamento": "Aferir a tensão de saída da fonte do painel principal para garantir estabilidade do CLP.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" }
    ],
    "Posimat": [
        { "id": "Posimat_0", "acao": "Melhoria do aéreo das multipet", "detalhamento": "Levando em consideração que Posimat é uma maquina nova em nossa planta e ela não apresenta anomalias mecânicas ate o momento, uma forma de melhorar o desempenho da linha seria melhorando ou desenvolvendo o aéreo das multipt set pois será nesse ponto que temos bastante ocorrencia.", "levantamento": "Dyone", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_1", "acao": "Validação dos Sensores de Posicionamento", "detalhamento": "Testar resposta dos sensores indutivos e ópticos. Reapertar suportes de fixação para evitar falsos alarmes por vibração.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_2", "acao": "Inspeção de Botoeiras e IHM", "detalhamento": "Testar integridade da tela da IHM, verificar funcionamento dos botões de comando físicos e sinaleiros luminosos.", "levantamento": "Leonardo Cardoso", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_3", "acao": "Ajuste das guias orientadoras", "detalhamento": "Fechar tolerâncias das guias do disco para evitar passagem de frascos deitados.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_4", "acao": "Ajuste de correias de saida", "detalhamento": "Inspecionar desgaste das correias que tracionam os frascos em pé e ajustar a tensão.", "levantamento": "Planejamento PCM", "execucao": "Orivaldo Camassuti", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_5", "acao": "Ajuste do sensor de acúmulo", "detalhamento": "Reposicionar a fotocélula de saída (calha) para sincronismo correto de parada.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" },
        { "id": "Posimat_6", "acao": "Inspeção do inversor de frequência", "detalhamento": "Verificar ventoinha de refrigeração e checar histórico de falhas no display.", "levantamento": "Planejamento PCM", "execucao": "Henrique Pereira", "previsao": "10/10/2026", "status": "Pendente" }
    ]
};